### ISSUE TITLE
macOS版的bundled包下载下来后要怎么打开和使用啊？

### ISSUE THREAD

**Issue by blacklein** [TransparentLC/realesrgan-gui#1]
如题

PS：请问能否用electron打包做成跨平台的app

**Comment by TransparentLC** [comment]
理论上在终端里 `chmod +x realesrgan-gui` 之后 `./realesrgan-gui` 就可以启动了，不过因为我没有可以运行 macOS 的设备所以只是做了打包但是并没有进一步的测试……

另外这个是用 Python 写的所以也算是跨平台了，但是和 Electron / Node.js 并不是同一套技术，而且 Electron 实在是太重了（

**Comment by blacklein** [comment]
我是M1 Pro的macbook pro，chmod、pip install -r都做了，无法运行

**Comment by TransparentLC** [comment]
有什么出错提示吗？

**Comment by blacklein** [comment]
`Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "darkdetect/__init__.py", line 14, in <module>
  File "distutils/version.py", line 52, in __lt__
  File "distutils/version.py", line 339, in _cmp
AttributeError: 'LooseVersion' object has no attribute 'version'
[16759] Failed to execute script 'main' due to unhandled exception: 'LooseVersion' object has no attribute 'version'
[16759] Traceback:
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "darkdetect/__init__.py", line 14, in <module>
  File "distutils/version.py", line 52, in __lt__
  File "distutils/version.py", line 339, in _cmp
AttributeError: 'LooseVersion' object has no attribute 'version'`

跳出上面的信息后就没反应了

**Comment by TransparentLC** [comment]
加载 darkdetect 时出了问题，虽然我没办法测试是怎么回事……

因为深色模式不影响主要功能，所以刚刚加了个 commit，把 `import darkdetect` 放进了 try except 里面，可以去 Actions 下载最新的 macOS 版的程序试一下还有没有这个问题。

**Comment by blacklein** [comment]
<img width="832" alt="截屏2022-06-02 18 05 13" src="https://user-images.githubusercontent.com/69177971/171606924-7ae03c7b-bcb3-4b27-83f1-c2e9e40a35de.png">

> Using executable: /Users/username/Downloads/realesrgan-gui-macos-bundled-v0.2.5.0/realesrgan-ncnn-vulkan
Traceback (most recent call last):
  File "task.py", line 217, in taskRunner
  File "task.py", line 95, in run
subprocess.CalledProcessError: Command '('/Users/username/Downloads/realesrgan-gui-macos-bundled-v0.2.5.0/realesrgan-ncnn-vulkan', '-v', '-i', '/Users/username/Desktop/2022-06-02.png', '-o', '/var/folders/5c/68bnmldx059fyp56djl1h6bh0000gn/T/T0XcfNx4mVeFeHRk.png', '-s', '4', '-t', '0', '-n', 'realesrgan-x4plus-anime', '-g', '0', '')' died with <Signals.SIGSEGV: 11>.

可以打开主界面了，但运行提示如上，没有输出放大后的图像

**Comment by TransparentLC** [comment]
直接在终端里调用 realesrgan-ncnn-vulkan 还会有 SIGSEGV 吗？比如按照这个提示写命令 `./realesrgan-ncnn-vulkan -v -i input.png -o output.png -s 4 -t 0 -n 'realesrgan-x4plus-anime -g 0`，不过如果这样也运行不了的话那也是realesrgan-ncnn-vulkan 本身而不是这个 GUI 的问题了……

**Comment by blacklein** [comment]
直接在终端调用realesrgan-ncnn-vulkan是没问题的。建议有可能的话还是做成electron的，重归重，但通用性还是可以的。

**Comment by blacklein** [comment]
下载最新bundle已解决
