### ISSUE TITLE
请问怎么用py2app把这个项目打包成mac app？

### ISSUE THREAD

**Issue by blacklein** [TransparentLC/realesrgan-gui#3]
请问怎么用py2app把这个项目打包成mac app？不是很懂，希望能帮忙指点下，谢谢哈

**Comment by TransparentLC** [comment]
py2app 是 macOS 限定的，因为我没有能运行 macOS 的设备所以就完全不知道怎么使用了（摊手

不过你可以参考一下这里使用的 pyinstaller 用的[打包配置文件](https://github.com/TransparentLC/realesrgan-gui/blob/master/realesrgan-gui.spec)。另外我查了一下，macOS 下的 app bundle 好像实际上就是一个特定结构的文件夹，也许你可以参考着[这个介绍](https://stackoverflow.com/questions/1596945#answer-3251285)直接用 release 里的二进制文件手工制作一个（repo 里有图标，但是需要自己转换成 icns 格式）。

**Comment by TransparentLC** [comment]
这样的话我也不清楚了……肥肠抱歉（对 macOS 完全不了解）

**Comment by blacklein** [comment]
请问如果我从main.py启动和运行程序，终端命令要怎么写？

**Comment by TransparentLC** [comment]
直接 `python3 /path/to/main.py` 应该就可以了。不过这样运行的话 Python 版本需要不低于 3.10。

**Comment by blacklein** [comment]
我研究了一些文献，用特定结构文件夹做成app，MacOS文件夹里应该只能有一个realesrgan-gui这一个binary，请问要怎么做能让realesrgan-gui从另外一个文件夹调用realesrgan-ncnn-vulkan，谢谢~

**Comment by blacklein** [comment]
如果用main.py启动的话，realesrgan-ncnn-vulkan和model是放在仓库根目录下吗？

**Comment by TransparentLC** [comment]
对，model 本来就是和 realesrgan-ncnn-vulkan 放在一起的，这个程序又会使用所在目录的 realesrgan-ncnn-vulkan，在代码里对应[这一行](https://github.com/TransparentLC/realesrgan-gui/blob/bcd7931a0e2d30948ee2d203ecae4f6606a6583c/define.py#L6)。

```python
RE_PATH = os.path.join(APP_PATH, 'realesrgan-ncnn-vulkan' + ('.exe' if os.name == 'nt' else ''))
```

**Comment by blacklein** [comment]
用main.py报错，下面是终端命令记录，不知道是缺了哪一步
<img width="762" alt="截屏2022-06-28 10 53 41" src="https://user-images.githubusercontent.com/69177971/176082143-40dfd33f-a54b-4856-8e03-d74533baf152.png">

**Comment by TransparentLC** [comment]
> 不过这样运行的话 Python 版本需要不低于 3.10。

也可以把那些 `match` 改成 `if ... elif ...`。

**Comment by blacklein** [comment]
python升级到3.10.4，报错信息变成下面这样了
![Uploading 截屏2022-06-28 11.10.17.png…]()

**Comment by TransparentLC** [comment]
`pip3 install -r requirements.txt`

切换 Python 大版本或虚拟环境之后应该是要重新安装依赖的。

**Comment by blacklein** [comment]
有点麻了，报错信息又变了
<img width="762" alt="截屏2022-06-28 11 22 39" src="https://user-images.githubusercontent.com/69177971/176085157-9408a36a-4a61-41be-bf01-458035839d28.png">

**Comment by TransparentLC** [comment]
看样子是因为你用的是 M1 但是那个用来处理拖拽的 TkinterDnD 只有 x64 的预编译版，也许需要把 Rosetta 2 装上……？

**Comment by blacklein** [comment]
那看来想要做成mac app是无解了

**Comment by blacklein** [comment]
请问能否把realesrgan-ncnn-vulkan和model打包进realesrgan-gui，做成一个binary可执行文件吗？

**Comment by TransparentLC** [comment]
其实 pyinstaller 是能做到把 realesrgan-ncnn-vulkan 和模型一起打包到可执行文件的，在 `realesrgan-gui.spec` 的 `Analysis(datas=...)` 里面把它们加上然后打包就可以了。不过我自己不会打算这么操作，因为 pyinstaller 打包的原理实际上是每次启动时把Python 环境和这些附带的文件一起解压到临时目录，关闭后再删掉，realesrgan-ncnn-vulkan 和模型加起来已经不小了每次启动还要解压一遍的话那性能有够差的（

想了想，如果只是要实现“双击就能打开”而不需要每次都打开终端的话，直接新建一个启动用的 Shell 脚本应该也可以……而且似乎有很多人都是[这么做](https://www.jianshu.com/p/8f78cd5f4b59)的。

**Comment by blacklein** [comment]
从我自己的体验来看，从终端打开的速度是有点慢的，可能跟我是M1芯片有关系，这个项目用起来比直接用realesrgan-ncnn-vulkan方便很多，所以还是想弄成mac app更方便日常使用，我这里main.py运行报错，可能跟环境和依赖包有关，估计打包也会失败，你若方便的话是否可以帮忙打个包，或者教我下打包的命令行，pyinstaller比py2app复杂很多，不会用，多谢了

**Comment by blacklein** [comment]
试了用`sudo pyinstaller realesrgan-gui.spec`进行打包，报错了
`❯ sudo pyinstaller realesrgan-gui.spec
25 INFO: PyInstaller: 5.1
25 INFO: Python: 3.10.4
32 INFO: Platform: macOS-12.4-arm64-arm-64bit
34 INFO: UPX is not available.
35 INFO: Extending PYTHONPATH with paths
['/Users/chenzhiyu/Downloads/realesrgan-gui']
100 INFO: checking Analysis
100 INFO: Building Analysis because Analysis-00.toc is non existent
100 INFO: Initializing module dependency graph...
101 INFO: Caching module graph hooks...
105 INFO: Analyzing base_library.zip ...
1793 INFO: Processing pre-find module path hook distutils from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1793 INFO: distutils: retargeting to non-venv dir '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10'
2268 INFO: Caching module dependency graph...
2329 INFO: running Analysis Analysis-00.toc
2332 INFO: Analyzing /Users/chenzhiyu/Downloads/realesrgan-gui/main.py
2607 INFO: Analyzing hidden import 'PIL._tkinter_finder'
2608 INFO: Processing module hooks...
2608 INFO: Loading module hook 'hook-tkinterdnd2.py' from '/Users/chenzhiyu/Downloads/realesrgan-gui/pyi-hooks'...
2612 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2612 INFO: Loading module hook 'hook-lib2to3.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2625 INFO: Loading module hook 'hook-_tkinter.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2626 INFO: Not collecting Tcl/Tk data - either python is using macOS' system Tcl/Tk framework, or Tcl/Tk data directories could not be found.
2626 INFO: Loading module hook 'hook-encodings.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2651 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2652 INFO: Loading module hook 'hook-distutils.util.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2652 INFO: Loading module hook 'hook-PIL.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2655 INFO: Loading module hook 'hook-platform.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2655 INFO: Loading module hook 'hook-PIL.Image.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2779 INFO: Loading module hook 'hook-pickle.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2780 INFO: Loading module hook 'hook-heapq.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2781 INFO: Loading module hook 'hook-difflib.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2781 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2781 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2788 INFO: Loading module hook 'hook-xml.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2806 INFO: Loading module hook 'hook-distutils.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2807 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks'...
2813 INFO: Looking for ctypes DLLs
2818 WARNING: Ignoring AppKit.framework/AppKit imported from /Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/darkdetect/_mac_detect.py - only basenames are supported with ctypes imports!
2820 INFO: Analyzing run-time hooks ...
2822 INFO: Including run-time hook '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
2822 INFO: Including run-time hook '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth_subprocess.py'
2823 INFO: Including run-time hook '/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/hooks/rthooks/pyi_rth__tkinter.py'
2825 INFO: Looking for dynamic libraries
2936 INFO: Looking for eggs
2936 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 842, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 764, in build
    exec(code, spec_namespace)
  File "realesrgan-gui.spec", line 12, in <module>
    a = Analysis(
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 319, in __init__
    self.__postinit__()
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 554, in assemble
    self._check_python_library(self.binaries)
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 658, in _check_python_library
    python_lib = bindepend.get_python_library_path()
  File "/Users/chenzhiyu/.pyenv/versions/3.10.4/lib/python3.10/site-packages/PyInstaller/depend/bindepend.py", line 928, in get_python_library_path
    raise IOError(msg)
OSError: Python library not found: Python3, .Python, Python, libpython3.10m.dylib, libpython3.10.dylib
    This means your Python installation does not come with proper shared library files.
    This usually happens due to missing development package, or unsuitable build parameters of the Python installation.

    * On Debian/Ubuntu, you need to install Python development packages:
      * apt-get install python3-dev
      * apt-get install python-dev
    * If you are building Python by yourself, rebuild with `--enable-shared` (or, `--enable-framework` on macOS).`

**Comment by TransparentLC** [comment]
想要通过 pyenv 安装的 Python 运行 pyinstaller 来打包的话，安装 Python 的时候需要[加上一个环境变量](https://pyinstaller.org/en/stable/development/venv.html)。

据我所知 Python 这边的所有打包工具都不能做到跨平台打包，所以我自己手动打包以及测试也只能照顾到自己主力使用的 Windows 和可以装虚拟机的 Linux。实际上 macOS 的打包也只是因为 GitHub Actions 正好支持 macOS 的系统镜像（这个镜像还是 x64 的，并不是 M1）而顺手加上去的而已，就像 readme 里面写的完全不能保证更多的可用性……所以和 macOS 相关的问题我确实没办法提供更多的帮助，自己翻文档以及拿着出错提示什么的去问 Google 应该会比我有用得多（

**Comment by blacklein** [comment]
我其实只有半桶水都没到，全靠baidu和google，目前看也确实没办法了，github只能上传25MB的附件，想用action来打包成一个binary也实现不了的样子，就目前这样子先用着了，感谢你的项目

**Comment by blacklein** [comment]
不好意思又来寻求作者帮助，我的操作如下
# 克隆仓库
git clone https://github.com/TransparentLC/realesrgan-gui.git

# 安装依赖
pip3 install -r requirements.txt # 此步骤无报错信息

# 创建.spec文件，完成后删除build和dist两个文件夹
pyinstaller -F main.py # 此步骤无报错信息

# 编辑.spec文件，修改后文如下
<img width="736" alt="截屏2022-06-30 16 01 00" src="https://user-images.githubusercontent.com/69177971/176625264-6a0ff8e2-2afb-454d-bcf1-6aaaf8c5eb64.png">

# 创建可执行程序
pyinstaller main.spec # 此步骤无报错信息

# 进入dist文件夹，运行生成的二进制可执行文件main
./main

运行报错信息如下：
<img width="762" alt="截屏2022-06-30 16 01 25" src="https://user-images.githubusercontent.com/69177971/176625306-0eb9d591-cee4-42c2-8628-830c2cff4511.png">

KeyError: 'en_US' 出错好像是多语言部分，但错误原因看不懂，求助作者，谢谢！

**Comment by blacklein** [comment]
还有个问题，仅仅是realesrgan-ncnn-vulkan和models加起来就有70多MB，但打包出来的binary只有50多MB，这是什么原因哈？

**Comment by TransparentLC** [comment]
多语言需要读取 i18n.ini 这个文件，打包的时候并没有带上它，所以就会出错了。需要参考仓库里的那个配置文件，在 `Analysis(datas=...)` 这里把其它几个需要打包的文件也加上。

原版 realesrgan-ncnn-vulkan 带上模型也只有 50 MB 左右啊……一定要推测什么原因的话，我估计是因为 pyinstaller 对打包的文件[使用 zlib 进行了压缩](https://github.com/pyinstaller/pyinstaller/blob/1a7d704ffbabb433007e3ba04750c2f13ade48e5/PyInstaller/archive/readers.py#L85)，把 realesrgan-ncnn-vulkan 和模型用 ZIP 压缩确实也能减少 15% 左右，和这个数值比较接近。

**Comment by TransparentLC** [comment]
稍微说一下如果一定要把 realesrgan-ncnn-vulkan 和模型一起打包进可执行文件的话需要改哪些地方，当然这个修改我是不会提交到仓库里面的，上面已经说过[原因](https://github.com/TransparentLC/realesrgan-gui/issues/3#issuecomment-1168237464)了（

* `main.py` 的 `modelFiles = set(os.listdir(os.path.join(define.APP_PATH, 'models')))` 以及 `define.py` 的 `RE_PATH = os.path.join(APP_PATH, 'realesrgan-ncnn-vulkan' + ('.exe' if os.name == 'nt' else ''))` 这两处，把 `APP_PATH` 都改成 `BASE_PATH`。
* `realesrgan-gui.spec` 的 `a = Analysis(datas=[...])` 那里加上 `('models', 'models'), ('realesrgan-ncnn-vulkan.exe', '.'), ('vcomp140.dll', '.'), ('vcomp140d.dll', '.')`，非 Windows 用户请去掉 exe 的扩展名和那两个 dll。
* 把 realesrgan-ncnn-vulkan 和模型放到项目目录。
* 打开终端，然后执行 `pyinstaller realesrgan-gui.spec`。

**Comment by blacklein** [comment]
非常感谢作者细心指导，已经按照上述办法打包mac APP成功，终于发现按照特定文件夹结构做的mac App会报错的问题出在哪里了：
# 1 打包成功，可以双击打开GUI，但放大图像运行报错
找了intel芯片的macbook pro，按上楼指示修改`main.py` `define.py` `realesrgan-gui.spec`, 把`realesrgan-ncnn-vulkan`和`models`放到项目目录，首次运行`pyinstaller realesrgan-gui.spec`，提示`Unable to find vcomp140` `Unable to find vcomp140d`，从`.spec`中删除`vcom140` `vcomp140d`后，再次运行`pyinstaller realesrgan-gui.spec`打包成功，双击能够打开GUI，从GUI的命令提示看，Using excutable对象realesrgan-ncnn-vulkan、models在macOS在系统临时文件夹内（进入临时文件夹确认该路径是真实有效的），但与按照特定文件夹结构做的mac App报了相同错误。
# 2 尝试找出问题所在
一开始，我怀疑是macOS的文件夹读写权限造成报错，抱着试一试的想法，我在终端运行了以下命令，试着用系统临时文件夹内的realesrgan-ncnn-vulkan和models去放大图像（系统临时文件夹地址忘记复制下来了，用特定文件夹结构的地址复现，经测试两者结果是一样的）
`/Users/username/Downloads/realesrgan-gui/dist/main.app/Contents/MacOS/realesrgan-ncnn-vulkan -i /Users/username/Downloads/realesrgan-gui/dist/main.app/Contents/MacOS/icon-1024px.png -o /Users/username/Downloads/realesrgan-gui/dist/main.app/Contents/MacOS/icon-1024px-x4.png`
结果报错无法运行，但改成下面这样就又能运行了：
`cd /Users/chenzhiyu/Downloads/realesrgan-gui/dist/main.app/Contents/MacOS/; ./realesrgan-ncnn-vulkan -i /Users/chenzhiyu/Downloads/realesrgan-gui/dist/main.app/Contents/MacOS/icon-1024px.png -o /Users/chenzhiyu/Downloads/realesrgan-gui/dist/main.app/Contents/MacOS/icon-1024px-x4.png`
另外还发现一个问题，系统临时文件夹内的realesrgan-ncnn-vulkan文件大小只有16MB左右，只有原本的一半，但文件变小后按照第二条命令仍然可以正常放大图像，而原本大小的realesrgan-ncnn-vulkan按照第一条命令一样会报错，所以文件大小变化似乎是不影响realesrgan-ncnn-vulkan工作的，系统临时文件夹内的models文件大小则毫无变化，原理猜测可能就是作者说的被压缩了吧。
# 3 问题总结
尝试用不同路径均能复现上述情况，因此判断不是系统文件夹读写权限造成无法运行，可能是realesrgan-ncnn-vulkan本身就可能不支持绝对路径调用可执行程序，因此不论是pyinstaller还是特定文件夹结构，两种方法打出来的mac App其实本质是一样的，最终都是一个特定文件夹结构的.app bundle，区别只是pyinstaller方法打出来的mac App每次运行会把realesrgan-ncnn-vulkan和model这两个释放到系统临时文件夹，并`using exectuable path_to_temp_folder/realesgran-ncnn-vulkan`，而特定文件夹结构做的mac app是`using exectuable path_to_app_folder/realesgran-ncnn-vulkan`，报错的本质原因应该是相同的。
# 4 解决思路
既然知道了需要先`cd`到`realesrgan-ncnn-vulkan`所在的目录，再运行`./realesrgan-ncnn-vulkan`调用就能正常运行可执行程序，那应该不需要用到pyinstaller打包，直接用作者最开始提示的特定文件夹结构打包mac App是最合理和最快捷的方法，问题关键在于让GUI输出的`using exectuable path_to_app_folder/realesgran-ncnn-vulkan`变成`cd path_to_app_folder; using excutable ./realesgran-ncnn-vulkan`（原理上应该是如此，先cd to working directory，后run executable binary）。
# 5 解决实践
我fork了项目，然后在fork的仓库里编辑了task.py（改了第76-79行，改动如下图），其他都不变，然后用action重新打包macos bundle
<img width="523" alt="截屏2022-07-01 09 40 31" src="https://user-images.githubusercontent.com/69177971/176805710-74286ad8-d33e-422b-959e-345a36351f4a.png">
下载action打包好的macos bundle（7MB左右那个），用特定文件夹结构打包成mac App，文件夹结构如下：
```
realesrgan-gui.app
└── Contents
    ├── Info.plist
    ├── Resources
    │   └── icon-1024px.icns
    └── macOS
        ├── config.ini
        ├── models
        │   ├── realesr-animevideov3-x2.bin
        │   ├── realesr-animevideov3-x2.param
        │   ├── realesr-animevideov3-x3.bin
        │   ├── realesr-animevideov3-x3.param
        │   ├── realesr-animevideov3-x4.bin
        │   ├── realesr-animevideov3-x4.param
        │   ├── realesrgan-x4plus-anime.bin
        │   ├── realesrgan-x4plus-anime.param
        │   ├── realesrgan-x4plus.bin
        │   └── realesrgan-x4plus.param
        ├── realesrgan-gui
        └── realesrgan-ncnn-vulkan

4 directories, 15 files
```
#### 问题1：realesrgan-gui.app能够打开GUI但界面是英文，如果是终端打开GUI是中文，原因不知
#### 问题2：运行报错
```
Using executable: /private/var/folders/5c/68bnmldx059fyp56djl1h6bh0000gn/T/AppTranslocation/8A17099D-4815-4EFC-A57C-F4BBB4FEBBAA/d/realesrgan-gui.app/Contents/macOS/realesrgan-ncnn-vulkan
Traceback (most recent call last):
  File "shutil.py", line 815, in move
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/5c/68bnmldx059fyp56djl1h6bh0000gn/T/aY1U-z6i_Ps9wBsD.png' -> '/Users/username/Downloads/realesrgan-gui/icon-1024px-x4.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "task.py", line 246, in taskRunner
  File "task.py", line 106, in run
  File "shutil.py", line 835, in move
  File "shutil.py", line 434, in copy2
  File "shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/5c/68bnmldx059fyp56djl1h6bh0000gn/T/aY1U-z6i_Ps9wBsD.png'
```
报错信息和用作者的macos bundle不一样了，应该是我改task.py出问题了，但不知道怎么改才能达到上面想要的效果，希望作者能够指导下，谢谢！

**Comment by TransparentLC** [comment]
在 Windows 和 Ubuntu 下面都试了一下，即使**工作目录和 realesrgan-ncnn-vulkan 所在目录不同**仍然是可以正常运行的，所以我也没办法解释，如果真的是**只有 macOS 下才有这个问题而另外两个系统没有**的话可以报告给原作者。以及 subprocess.Popen 是用来启动进程的而不是运行 Shell 命令，我估计不应该在里面写 cd 而应该使用 `os.chdir` 修改工作目录（修改后会不会影响后续操作我就没分析了），用到的临时文件的路径都是绝对路径，按理来说不应该受工作目录影响的……

语言是使用 `locale.getdefaultlocale()` 判断的，据说 macOS 下双击打开的程序和在终端里启动环境变量会不一样（参见[这里](https://stackoverflow.com/questions/4719789#answer-4719920)），又查了一下在 Info.plist 里可以钦定，比如想要设成简体中文的话就加上：

```xml
<key>LSEnvironment</key>
<dict>
    <key>LANG</key>
    <string>zh_CN.UTF-8</string>
</dict>
```

**Comment by blacklein** [comment]
按照上面的方法，添加LSEnvironment后，GUI变成简体中文了，但运行报错依旧。
然后试了下，终端输入`/Users/username/Desktop/realesrgan-gui.app/Contents/macOS/realesrgan-gui`可以直接启动GUI，但放大图像会报错，但终端先输入`cd /Users/chenzhiyu/Desktop/realesrgan-gui.app/Contents/macOS`再输入`./realesrgan-gui`启动GUI并放大图像就能正常运行，所以似乎跟路径里面有`.app`后缀也没关系

**Comment by TransparentLC** [comment]
也就是说在 `***.app/Contents/macOS` 以外的工作目录调用这个目录下的 realesrgan-ncnn-vulkan 就不能正常运行？这样的话我建议再测试一下，把这里的 realesrgan-ncnn-vulkan 替换成用了相同框架的 [waifu2x-ncnn-vulkan](https://github.com/nihui/waifu2x-ncnn-vulkan) 或其它的命令行程序（严谨一点还可以限定这个程序也需要使用 GPU 什么的），再按照上面的方式在终端里启动，看看能不能正常运行。

我不知道 macOS 对这个目录是不是有什么特别的处理或限制。总之如果真的是只有 realesrgan-ncnn-vulkan 有这个问题，那就可以开个 Issue 报告原作者了。

**Comment by blacklein** [comment]
相同方法测试了`waifu2x-ncnn-vulkan`，输入`/Users/username/Downloads/waifu2x-ncnn-vulkan-20220419-macos/waifu2x-ncnn-vulkan -i /Users/username/Pictures/Untitled.png -o /Users/username/Pictures/Untitled-4x.png`是可以正常放大图像的
```
[0 Apple M1 Max]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Apple M1 Max]  bugsbn1=0  bugbilz=97  bugcopc=0  bugihfa=0
[0 Apple M1 Max]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Apple M1 Max]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
```
也就是说，如果这个项目也可以用于`waifu2x-ncnn-vulkan`的话，理论上应该可以直接通过特定结构文件夹方式打包成mac App，而且`waifu2x-ncnn-vulkan`支持M1芯片的神经引擎，放大速度极快，会非常方便，希望作者考虑下做个waifu2x版哈哈，理论上应该没有难度。
realesrgan-ncnn-vulkan的issue报告原作者的问题，我是打算去报告下，万一原作者看到了呢，不过从那边issue列表的情况看，作者基本不回不管这个项目的样子，不知道报告了有没有用了

**Comment by TransparentLC** [comment]
因为这几个程序参数都差不多，这个 GUI 的代码也不多，处理 GIF 之类的部分都是通用的，所以想要改的人就 fork 之后自己动手吧，应该没什么难度～

因为不能在 app bundle 里运行看样子不属于这个 GUI 本身的问题，所以这个 issue 就先 close 了。

**Comment by TransparentLC** [comment]
因为这几个程序参数都差不多，这个 GUI 的代码也不多，处理 GIF 之类的部分都是通用的，所以想要改的人就 fork 之后自己动手吧，应该没什么难度～

因为不能在 app bundle 里运行看样子不属于这个 GUI 本身的问题，所以这个 issue 就先 close 了。
